config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'article/:id' => 'article#show', as:'article'

  get 'game/:game_id' => 'games#show', as: 'game'

  get 'signup'  => 'users#new' 
  resources :users

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  namespace :admin do
    resources :article

    get '/' => 'pages#index', as:'root'
  end









end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
	DISQUS_SHORTNAME = Rails.env == "development" ? "akrion-dev".freeze : "akrion-porduction".freeze
end

app/models/games.rb
class Games < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	def editor? 
		self.role == 'editor' 
	end
end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < ApplicationController
layout 'adminpanel'

	def index

	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


	helper_method :current_user 

	def current_user 
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def require_user 
		redirect_to '/login' unless current_user 
	end

	def require_editor
			redirect_to '/' unless current_user.editor?
	end
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController	
	def show
		@article = Article.find(params[:id])
	end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	def show
		@game_id = params[:game_id]
		@article = Article.where(:game_id => @game_id)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
layout 'adminpanel'
	
	def new

	end

	def create
		@user = User.find_by_email(params[:session][:email])
		if @user && @user.authenticate(params[:session][:password])
			session[:user_id] = @user.id
			redirect_to '/admin'
		else
			redirect_to 'login'
		end 
	end

	def destroy 
		session[:user_id] = nil 
		redirect_to '/' 
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
layout 'adminpanel'
	
	def new
		@user = User.new
	end

	def create 
		@user = User.new(user_params) 
		if @user.save 
			session[:user_id] = @user.id 
			redirect_to '/' 
		else 
			redirect_to '/signup' 
		end 
	end
	
	private
		def user_params
			params.require(:user).permit(:name, :email, :password)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@article = Article.all.limit("5")
	end
end

app/helpers/admin/article_helper.rb
module Admin::ArticleHelper
end

app/helpers/admin/pages_helper.rb
module Admin::PagesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_article.html.erb
<div id="lates-news" class="center">
	<h3>Последни новини</h3>
	<hr>
	
	<% @article.each do |data|%>
	<div class="article">
		<div class="article-image">
			<%= image_tag "bg2.jpg" %>
		</div>
		<div class="article-content center">
			<div class="top">
				<%= data.name %><span id="color">- <%= Games.find(data.game_id).name %> - <%= data.created_at.strftime("%d.%m.%Y") %></span>
			</div>
			<div class="article-name">
				<%= data.articlename %>
			</div>
			<p><%= data.articlecontent %></p>
			<%= link_to "Прочети повече", article_path(data.id), :class => "more" %>
		</div>
	</div>
	<% end %>

</div>

<div id="load">
	Зареди повече новини.
</div>

app/views/layouts/_disqus.html.erb
<div id="disqus_thread" class="center"></div>
<script type="text/javascript">

	var disqus_shortname = '<%= Article::DISQUS_SHORTNAME %>';
	var disqus_identifier = '<%= @article.id %>';
	var disqus_url = '<%= request.original_url %>';

	/* * * DON'T EDIT BELOW THIS LINE * * */
	(function() {
		var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
		dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
		(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
	})();
</script>

app/views/layouts/_footer.html.erb
<div id="footer">
	<div id="columns">
		<div id="about" class="col">
			<h2>За нас</h2>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur egestas posuere libero at ullamcorper. Etiam nec odio non ante finibus ultrices vel ultrices </p>
		</div>
		<div id="archive" class="col">
			<h2>Архив</h2>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur egestas posuere libero at ullamcorper. Etiam nec odio non ante finibus ultrices vel ultrices </p>
		</div>
		<div id="social" class="col">
			<h2>Социални мрежи</h2>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur egestas posuere libero at ullamcorper. Etiam nec odio non ante finibus ultrices vel ultrices </p>
		</div>
		<div class="clear"></div>
	</div>
	<h5>© 2015 Името на проекта. Всички права са запазени</h5>
</div>

app/views/layouts/_header.html.erb
<div id="header">
	<ul id="menu">
		<li><%= link_to "LOGO", root_path %></li>
		<li>
			<a href="#">Игри &#9662;</a>
			<ul class="dropdown">
				<li><%= link_to image_tag("minecraft.png", :class => "logo"), game_path('1') %></li>
				<li><%= link_to image_tag("csgo.png", :class => "logo"), game_path('2') %></li>
				<li><%= link_to image_tag("hos.png", :class => "logo"), game_path('3') %></li>
				<li><%= link_to image_tag("wow.png", :class => "logo"), game_path('4') %></li>
				<li><%= link_to image_tag("lol.png", :class => "logo"), game_path('5') %></li>
			</ul>
		</li>
		<li><%= link_to "Форум", root_path %></li>
	</ul>

	<div id="search">
		<form action="#">
			<input type="text" name="search" placeholder="Търси...">
		</form>
	</div>
	<div class="clear"></div>
</div>

app/views/layouts/_slider.html.erb
<div id="slider" class="owl-carousel">
	<div>
		<%= link_to root_path do %>
			<%= image_tag ("bg.jpg"), :class => 'sliderimage' %>
			<h1 id="name">Иметео на новината</h1>
		<% end %>
	</div>
	<div>
		<%= link_to root_path do %>
			<%= image_tag ("bg.jpg"), :class => 'sliderimage' %>
			<h1 id="name">Иметео на новината</h1>
		<% end %>
	</div>
	<div>
		<%= link_to root_path do %>
			<%= image_tag ("bg.jpg"), :class => 'sliderimage' %>
			<h1 id="name">Иметео на новината</h1>
		<% end %>
	</div>
	<div>
		<%= link_to root_path do %>
			<%= image_tag ("bg.jpg"), :class => 'sliderimage' %>
			<h1 id="name">Иметео на новината</h1>
		<% end %>
	</div>
	<div>
		<%= link_to root_path do %>
			<%= image_tag ("bg.jpg"), :class => 'sliderimage' %>
			<h1 id="name">Иметео на новината</h1>
		<% end %>
	</div>
</div>

app/views/layouts/_submenu.html.erb
<div id="submenu">
	<ul>
		<li class="selected"><%= link_to "Редстоун", root_path %></li>
		<li><%= link_to "Постройки", root_path %></li>
		<li><%= link_to "Модове", root_path %></li>
		<li><%= link_to "Новини", root_path %></li>
		<li><%= link_to "ьяьяа", root_path %></li>
		<li><%= link_to "ьяаьяа", root_path %></li>
	</ul>
</div>

app/views/layouts/adminpanel.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= stylesheet_link_tag	'adminpanel', media: 'all', 'data-turbodivnks-track' => true %>
  <%= javascript_include_tag 'adminpanel', 'data-turbodivnks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="contrast-red login contrast-background">
	
	<%= yield %>
	
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= stylesheet_link_tag	'application', media: 'all', 'data-turbodivnks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbodivnks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render "layouts/header" %>
	
	<%= yield %>

	<%= render "layouts/footer" %>
	
</body>
</html>